# -*- coding: utf-8 -*-
"""Class Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dkqnG6LL_HzyFHUzxUOIzNd-u8cbe-Lq
"""

#1.1

x = input("First number: ")
print(x)

y = input("Second number: ")
print(y)

#1.2

x = int(input("First number: "))
y = int(input("Second number: "))

print(f"The summation will be: {x+y}")

print(f"The multiplication will be: {x*y}")

#1.3

x = int(input("Integer: "))
y = float(input("Float: "))

print(f"Addition of the numbers: {x+y}")
print(f"Subtraction of the numbers: {x-y}")

#1.4

x = int(input("First integer: "))
y = int(input("Second integer: "))

x = str(x)
y = float(y)

y = str(y)

print(x+y)